// Objective-C API for talking to github.com/kkdai/webdl Go package.
//   gobind -lang=objc github.com/kkdai/webdl
//
// File is generated by gobind. Do not edit.

#ifndef __GoWebdl_H__
#define __GoWebdl_H__

#include <Foundation/Foundation.h>

@class GoWebdlWebpic;

@interface GoWebdlWebpic : NSObject {
}
@property(strong, readonly) id ref;

- (id)initWithRef:(id)ref;
- (NSString*)BaseDir;
- (void)setBaseDir:(NSString*)v;
- (BOOL)BigDecodeUTF8:(NSData*)s ret0_:(NSData**)ret0_ error:(NSError**)error;
- (void)Crawler:(NSString*)target workerNum:(int)workerNum;
- (BOOL)HasValidUrl:(NSString*)url;
- (void)ReloadParser:(NSString*)jsonFileAddr;
- (void)UpdateParser:(NSString*)jsonAddr;
@end

FOUNDATION_EXPORT GoWebdlWebpic* GoWebdlNew();

#endif
