language: ruby
cache: bundler

language: objective-c
cache:
  - bundler
  - cocoapods

install: bundle exec pod install
script: xcodebuild -workspace photoviewer.xcworkspace -scheme Toast -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO