// Objective-C API for talking to github.com/kkdai/photomgr Go package.
//   gobind -lang=objc -prefix=Go github.com/kkdai/photomgr
//
// File is generated by gobind. Do not edit.

#ifndef __GoPhotomgr_H__
#define __GoPhotomgr_H__

#include <Foundation/Foundation.h>
#include "GoUniverse.h"

@class GoPhotomgrCK101;
@class GoPhotomgrFBAlbum;
@class GoPhotomgrPTT;

@interface GoPhotomgrCK101 : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)baseDir;
- (void)setBaseDir:(NSString*)v;
- (void)crawler:(NSString*)target workerNum:(long)workerNum;
- (long)getCurrentPageResultCount;
- (long)getPostStarByIndex:(long)postIndex;
- (NSString*)getPostTitleByIndex:(long)postIndex;
- (NSString*)getPostUrlByIndex:(long)postIndex;
// skipped method CK101.GetUrlPhotos with unsupported parameter or return types

- (BOOL)hasValidURL:(NSString*)url;
- (long)parseCK101PageByIndex:(long)page;
@end

@interface GoPhotomgrFBAlbum : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)baseDir;
- (void)setBaseDir:(NSString*)v;
- (void)crawler:(NSString*)target workerNum:(long)workerNum;
- (long)getCurrentPageResultCount;
- (long)getPostStarByIndex:(long)postIndex;
- (NSString*)getPostTitleByIndex:(long)postIndex;
- (NSString*)getPostUrlByIndex:(long)postIndex;
- (BOOL)hasValidURL:(NSString*)url;
- (long)parseFBAlbumPageByIndex:(long)page;
@end

@interface GoPhotomgrPTT : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)baseDir;
- (void)setBaseDir:(NSString*)v;
- (void)crawler:(NSString*)target workerNum:(long)workerNum;
- (long)getCurrentPageResultCount;
- (long)getPostStarByIndex:(long)postIndex;
- (NSString*)getPostTitleByIndex:(long)postIndex;
- (NSString*)getPostUrlByIndex:(long)postIndex;
// skipped method PTT.GetUrlPhotos with unsupported parameter or return types

- (BOOL)hasValidURL:(NSString*)url;
- (long)parsePttPageByIndex:(long)page;
@end

FOUNDATION_EXPORT GoPhotomgrCK101* GoPhotomgrNewCK101();

FOUNDATION_EXPORT GoPhotomgrFBAlbum* GoPhotomgrNewFBAlbum();

FOUNDATION_EXPORT GoPhotomgrPTT* GoPhotomgrNewPTT();

#endif
