// Objective-C API for talking to github.com/kkdai/photomgr Go package.
//   gobind -lang=objc github.com/kkdai/photomgr
//
// File is generated by gobind. Do not edit.

#ifndef __GoPhotomgr_H__
#define __GoPhotomgr_H__

#include <Foundation/Foundation.h>

@class GoPhotomgrPTT;

@interface GoPhotomgrPTT : NSObject {
}
@property(strong, readonly) id ref;

- (id)initWithRef:(id)ref;
- (NSString*)BaseDir;
- (void)setBaseDir:(NSString*)v;
- (void)Crawler:(NSString*)target workerNum:(int)workerNum;
- (int)GetCurrentPageResultCount;
- (int)GetPostStarByIndex:(int)postIndex;
- (NSString*)GetPostTitleByIndex:(int)postIndex;
- (NSString*)GetPostUrlByIndex:(int)postIndex;
- (BOOL)HasValidURL:(NSString*)url;
- (int)ParsePttPageByIndex:(int)page;
@end

FOUNDATION_EXPORT GoPhotomgrPTT* GoPhotomgrNewPTT();

#endif
