
// Objective-C API for talking to the following Go packages
//
//	github.com/kkdai/photomgr
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Photomgr_H__
#define __Photomgr_H__

#include "GoPhotomgr.h"
#include "GoUniverse.h"

#endif
